Esta sección se centrará sólo en matrices 2D pero puedes usar numpy para construir conjuntos de dimensiones mucho mayores.
En este vídeo, cubriremos los conceptos básicos y la creación de matrices en 2D, indexación y corte en 2D, y operaciones básicas en 2D.

Considere la lista `a`, la lista contiene tres listas anidadas, cada una de ellas del mismo tamaño.

Cada lista está codificada por colores para simplificar.

Podemos convertir la lista en una matriz numpy de la siguiente manera:

In [8]:
import numpy as np

# Crear una matriz 2D
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Es útil visualizar la matriz numpy como una matriz rectangular. Cada una de las listas anidadas corresponde a una fila diferente de la matriz. Podemos usar el atributo `ndim` para obtener el número de ejes o dimensiones, denominado rango. El término rango no se refiere al número de columnas linealmente independientes como una matriz. Es útil pensar en `ndim` como el número de listas anidadas.

In [9]:
print(a.ndim)  # Imprime el número de dimensiones: 2

2


La forma del atributo devuelve una tupla. El primer elemento de la tupla corresponde al número de listas anidadas contenidas en la lista original o el número de filas en la representación rectangular, en este caso tres. El segundo elemento corresponde al tamaño de cada una de las listas anidadas o el número de columnas en la matriz rectangular, en este caso tres.

In [10]:
print(a.shape)  # Imprime la forma de la matriz: (3, 3)

(3, 3)


El atributo `size` nos da el tamaño total de la matriz. Multiplicando el número de columnas y filas juntas, obtenemos el número total de elementos, en este caso nueve.

In [11]:
print(a.size)  # Imprime el número total de elementos: 9

9


Podemos utilizar corchetes rectangulares para acceder a los diferentes elementos del array. El primer índice corresponde a la fila y el segundo al elemento de la columna. Considere el siguiente ejemplo:

In [12]:
# Acceder a elementos específicos
print(a[1, 2])  # Imprime el valor en la segunda fila, tercera columna: 6
print(a[0, 0])  # Imprime el valor en la primera fila, primera columna: 1


6
1


También podemos usar el corte en matrices 2D. El primer índice especifica las filas, y el segundo las columnas. Considere este ejemplo:

In [13]:
# Corte en matrices 2D
print(a[0:2, 1:3])  # Imprime un subarray: [[2 3], [5 6]]


[[2 3]
 [5 6]]


Podemos sumar matrices de la misma forma que sumamos arrays:

In [14]:
# Sumar matrices
b = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
suma = a + b
print(suma)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Multiplicar una matriz numpy por un escalar es idéntico a multiplicar una matriz por un escalar:

In [15]:
# Multiplicar una matriz por un escalar
escalar = 2
resultado = a * escalar
print(resultado)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


El producto de Hadamard corresponde a multiplicar cada uno de los elementos en la misma posición:

In [16]:
# Producto de Hadamard
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
producto_hadamard = a * c
print(producto_hadamard)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Para la multiplicación de matrices, asegúrate de que el número de columnas en la matriz A es igual al número de filas de la matriz B. El resultado es una nueva matriz:

In [17]:
# Multiplicación de matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 4], [2, 5], [3, 6]])
C = np.dot(A, B)
print(C)

[[14 32]
 [32 77]]


Hay mucho más que puedes hacer con Numpy. Visita [Numpy](https://numpy.org) para más detalles.